# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mP9UCgf-E8MNqP2jmlXLwzmGh8H02bWN
"""

import pandas as pd
df = pd.DataFrame({'Ism':['Alijon','Sarvinoz','Muxbira','Farog\'at','Shaxzod','Muhammadjon'],
                 'Familiyasi':['Toxtasinov','Yusufjonov','Boymirzayev','Abdurasulova','yulchiyeva','Ubaydullayev'],
                 'Yoshi':['18','19','19','20','19','18'],
                 'Kursi':['2','2','2','2','2','2'],
                 })
print(df)

df.to_excel('guruh.xlsx',index=False,sheet_name='Sheet1')